# Define here dictionaries of default params 
# these will be attached to the LookupTable Task object
# The idea is to offer sensible and reproducible 
# default suggestions of parameters for datasets 
# which have been used in past papers
task_defaults:
    batch_size: 128
    k: 3
    max_len: 60
    patience: 5
    epochs: 20